# Server
server:
  port: 8085

# Spring
spring:
  kafka:
    bootstrap-servers: localhost:9092

# Logging
logging:
  level:
    root: INFO
    com.mathisdulieu.ticketing: DEBUG
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr([%thread]){blue} %clr(%-5level){green} %clr(%logger{36}){cyan} - %msg%n"
